spring:
  profiles:
    active: dev
# 配置数据库信息
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-note?connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
# 配置redis缓存信息
  redis:
    host: 127.0.0.1
    port: 6379
    # 如果Redis设置了密码，添加如下配置
    password: redis@1234

#配置服务端口及上下文
server:
  port: 8086
  servlet:
    context-path: /note


